name: Lint Code

on:
  push:
    branches: [ main, lint ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1

      - name: Install Linter
        run: go install golang.org/x/lint/golint

      - name: Lint the project
        run: |
          if ! golint ./...; then
            echo "Go lint has found issues, please fix the changes for successful merge"
            exit 1
          fi

